services:
  mailpit:
    image: axllent/mailpit:v1.20.4
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8025/readyz"]
      interval: "1s"
      retries: 10
      start_period: 1s
      start_interval: 1s
