name: Test Application

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Dependencies
        run: docker compose up -d

      - name: Compile the Test
        run: go test -coverprofile=coverage.out -c -o gomtp.test ./cmd/

      - name: Test the Application
        run: ./gomtp.test -test.coverprofile ./c.out | tee testCoverage.out

      - name: Check Coverage If Higher Than 80
        run: |
          export coverage=$(grep -oP '(?<=coverage: )[0-9.]+' testCoverage.out)
          expr $coverage '>' 85
