name: Test Application

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Dependencies
        run: docker compose up -d

      - name: Wait 10 seconds before mailhog gets ready
        run: sleep 10

      - name: Compile the Test
        run: go test -coverprofile=coverage.out -c -o gomtp.test ./cmd/

      - name: Test the Application
        run: | 
          set -e
          ./gomtp.test -test.coverprofile ./c.out | tee testCoverage.out
          exit ${PIPESTATUS[0]}

      - name: Check Coverage If Higher Than 85
        run: |
          export coverage=$(grep -oP '(?<=coverage: )[0-9.]+' testCoverage.out)
          echo "$coverage" | awk -v threshold=85 '{if ($1 > threshold) exit 0; else exit 1}'
