name: Test Application

on:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Dependencies
        run: docker compose up -d

      - name: Test the Application
        run: go test -c -o gomtp.test ./cmd && ./gomtp.test
